import * as React from "react"
import { motion, AnimatePresence } from "framer-motion"
import { useNavigate } from "react-router-dom"
import { useAuth } from "@clerk/react"
import { Menu, X, ArrowRight, Zap, Wifi, Sparkles, Trophy, Palette } from "lucide-react"
import { ThemeSwitcher } from "@/components/ui/theme-switcher"

// Utility function
const cn = (...classes: (string | undefined | null | false)[]) => classes.filter(Boolean).join(" ")

// Button Component
interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "default" | "outline" | "ghost"
  size?: "default" | "sm" | "lg"
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant = "default", size = "default", children, ...props }, ref) => {
    const variantClasses = {
      default: "bg-primary text-primary-foreground hover:bg-primary/90 shadow-sm",
      outline: "border border-border bg-transparent text-foreground hover:bg-accent hover:text-accent-foreground",
      ghost: "text-primary hover:underline bg-transparent px-0",
    }
    const sizeClasses = {
      default: "h-10 px-5 py-2 text-sm",
      sm: "h-8 px-4 text-xs",
      lg: "h-12 px-8 text-base",
    }
    return (
      <button
        className={cn(
          "inline-flex items-center justify-center rounded-full font-medium transition-all duration-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 active:scale-[0.98]",
          variantClasses[variant],
          sizeClasses[size],
          className
        )}
        ref={ref}
        {...props}
      >
        {children}
      </button>
    )
  }
)
Button.displayName = "Button"

// Animation variants
const fadeIn = {
  hidden: { opacity: 0, y: 30 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.8, ease: [0.22, 1, 0.36, 1] },
  },
}

const staggerContainer = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
      delayChildren: 0.1,
    },
  },
}

const itemFadeIn = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] },
  },
}

// Feature Component
interface FeatureProps {
  icon: React.ReactNode
  title: string
  description: string
  index: number
}

const Feature: React.FC<FeatureProps> = ({ icon, title, description, index }) => {
  return (
    <motion.div
      variants={itemFadeIn}
      className={cn(
        "relative flex flex-col p-12 bg-muted/50 rounded-[28px] group overflow-hidden border border-transparent hover:border-border transition-all duration-500",
      )}
    >
      <div className="relative z-10 mb-8 text-foreground transition-transform duration-500 group-hover:scale-105">
        {icon}
      </div>
      <div className="relative z-10">
        <h3 className="text-2xl font-semibold mb-4 text-foreground tracking-tight">
          {title}
        </h3>
        <p className="text-muted-foreground leading-relaxed text-lg font-medium tracking-tight">
          {description}
        </p>
      </div>
    </motion.div>
  )
}

const Landing = () => {
  const navigate = useNavigate()
  const { isSignedIn, isLoaded } = useAuth()
  const [isMenuOpen, setIsMenuOpen] = React.useState(false)
  const [scrollY, setScrollY] = React.useState(0)

  React.useEffect(() => {
    const handleScroll = () => setScrollY(window.scrollY)
    window.addEventListener("scroll", handleScroll)
    return () => window.removeEventListener("scroll", handleScroll)
  }, [])

  const features = [
    {
      icon: <Wifi className="h-10 w-10" />,
      title: "Real-time Precision",
      description: "Experience zero-latency stroke synchronization. Every line you draw is seen instantly by everyone in the arena.",
    },
    {
      icon: <Sparkles className="h-10 w-10" />,
      title: "AI-Driven Prompts",
      description: "Infinite unique drawing challenges generated by Gemini AI. No two rounds are ever the same.",
    },
    {
      icon: <Trophy className="h-10 w-10" />,
      title: "Global Competition",
      description: "Climb the ranks and prove your mastery. Earn points for speed and accuracy in a global arena.",
    },
  ]

  if (!isLoaded) return null

  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground antialiased selection:bg-primary selection:text-primary-foreground overflow-x-hidden">
      {/* Header */}
      <motion.header
        initial={{ y: -100 }}
        animate={{ y: 0 }}
        transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
        className={cn(
          "fixed top-0 z-50 w-full transition-all duration-500 px-6 md:px-12",
          scrollY > 20 ? "bg-background/80 backdrop-blur-xl border-b border-border py-2" : "bg-transparent py-4"
        )}
      >
        <div className="container mx-auto flex h-12 items-center justify-between">
          <motion.div
            whileHover={{ opacity: 0.7 }}
            transition={{ duration: 0.2 }}
          >
            <a href="/" className="text-xl font-semibold tracking-tight flex items-center gap-2">
              <Palette className="w-6 h-6" />
              InkArena
            </a>
          </motion.div>

          <nav className="hidden md:flex items-center gap-8">
            {["Features", "Competition", "About"].map((item) => (
              <motion.a
                key={item}
                href={`#${item.toLowerCase()}`}
                className="text-xs font-medium text-foreground opacity-80 hover:opacity-100 transition-opacity duration-300"
              >
                {item}
              </motion.a>
            ))}
          </nav>

          <div className="hidden md:flex items-center gap-6">
            <ThemeSwitcher />
            {isSignedIn ? (
              <Button size="sm" onClick={() => navigate("/lobby")}>
                Go to Lobby
              </Button>
            ) : (
              <>
                <Button variant="ghost" size="sm" onClick={() => navigate("/login")}>
                  Sign In
                </Button>
                <Button size="sm" onClick={() => navigate("/login")}>
                  Enter Arena
                </Button>
              </>
            )}
          </div>

          <button className="flex md:hidden p-2" onClick={() => setIsMenuOpen(!isMenuOpen)}>
            {isMenuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
          </button>
        </div>
      </motion.header>

      {/* Mobile Menu */}
      <AnimatePresence>
        {isMenuOpen && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            transition={{ duration: 0.4, ease: [0.22, 1, 0.36, 1] }}
            className="fixed top-16 left-0 right-0 z-40 bg-background border-b border-border md:hidden shadow-xl"
          >
            <nav className="flex flex-col p-6 gap-4">
              {["Features", "Competition", "About"].map((item) => (
                <a
                  key={item}
                  href={`#${item.toLowerCase()}`}
                  className="text-base font-medium p-2 hover:bg-muted rounded-lg transition-colors"
                  onClick={() => setIsMenuOpen(false)}
                >
                  {item}
                </a>
              ))}
              <div className="flex flex-col gap-3 pt-4 border-t border-border">
                <div className="flex justify-center py-2">
                    <ThemeSwitcher />
                </div>
                <Button className="w-full" onClick={() => navigate(isSignedIn ? "/lobby" : "/login")}>
                  {isSignedIn ? "Go to Lobby" : "Enter Arena"}
                </Button>
              </div>
            </nav>
          </motion.div>
        )}
      </AnimatePresence>

      <main className="flex-1">
        {/* Hero Section */}
        <section className="relative pt-32 pb-20 md:pt-48 md:pb-32 lg:pt-56 lg:pb-40">
          <div className="container mx-auto px-6 lg:px-12">
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeIn}
              className="max-w-4xl mx-auto text-center"
            >
              <motion.h1
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 1, delay: 0.2, ease: [0.22, 1, 0.36, 1] }}
                className="text-5xl md:text-7xl lg:text-8xl font-semibold tracking-tight mb-8 leading-[1.05] text-foreground"
              >
                InkArena.
                <br />
                <span className="text-muted-foreground">Precision meets play.</span>
              </motion.h1>

              <motion.p
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 1, delay: 0.4, ease: [0.22, 1, 0.36, 1] }}
                className="text-xl md:text-2xl text-muted-foreground mb-12 max-w-2xl mx-auto leading-relaxed font-medium tracking-tight"
              >
                The ultimate real-time drawing competition. Sophisticated tools, global lobbies, and endless creativity.
              </motion.p>

              <motion.div
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 1, delay: 0.6, ease: [0.22, 1, 0.36, 1] }}
                className="flex flex-col sm:flex-row gap-6 justify-center items-center"
              >
                <Button size="lg" className="group" onClick={() => navigate(isSignedIn ? "/lobby" : "/login")}>
                  {isSignedIn ? "Go to Lobby" : "Enter Arena"}
                  <ArrowRight className="ml-2 h-5 w-5 group-hover:translate-x-1 transition-transform" />
                </Button>
                <button 
                  onClick={() => document.getElementById("features")?.scrollIntoView({ behavior: "smooth" })}
                  className="text-primary hover:underline flex items-center gap-1 text-lg font-medium"
                >
                  Learn more <ArrowRight className="h-4 w-4" />
                </button>
              </motion.div>
            </motion.div>
          </div>
        </section>

        {/* Features Section */}
        <section id="features" className="py-24 md:py-32 lg:py-48 bg-muted/20">
          <div className="container mx-auto px-6 lg:px-12">
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeIn}
              className="max-w-3xl mx-auto text-center mb-24"
            >
              <motion.h2
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8 }}
                className="text-4xl md:text-5xl lg:text-6xl font-semibold tracking-tight mb-6"
              >
                Built for Mastery.
              </motion.h2>
              <motion.p
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.2 }}
                className="text-xl text-muted-foreground font-medium tracking-tight leading-relaxed"
              >
                Sleek tools and powerful synchronization that stay out of your way. Focus on the art of the guess.
              </motion.p>
            </motion.div>

            <motion.div
              variants={staggerContainer}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              className="grid grid-cols-1 md:grid-cols-3 gap-8"
            >
              {features.map((feature, index) => (
                <Feature key={index} {...feature} index={index} />
              ))}
            </motion.div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-24 md:py-32 lg:py-48">
          <div className="container mx-auto px-6 lg:px-12">
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeIn}
              className="max-w-5xl mx-auto text-center"
            >
              <motion.h2
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8 }}
                className="text-5xl md:text-7xl font-semibold tracking-tight mb-10 leading-none"
              >
                Ready to dominate the canvas?
              </motion.h2>
              <motion.p
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.2 }}
                className="text-xl md:text-2xl text-muted-foreground mb-12 max-w-2xl mx-auto font-medium tracking-tight"
              >
                Join thousands of creators in the most sophisticated drawing game ever built.
              </motion.p>
              <motion.div
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.4 }}
              >
                <Button size="lg" onClick={() => navigate(isSignedIn ? "/lobby" : "/login")}>
                  Start Playing
                </Button>
              </motion.div>
            </motion.div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="bg-muted/50 border-t border-border py-16 md:py-24">
        <div className="container mx-auto px-6 lg:px-12">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-16 mb-16">
            <div className="md:col-span-2 space-y-6">
              <h3 className="text-xl font-semibold tracking-tight flex items-center gap-2">
                <Palette className="w-6 h-6" />
                InkArena
              </h3>
              <p className="text-muted-foreground font-medium text-base leading-relaxed max-w-sm tracking-tight">
                A professional-grade drawing arena for creators who value precision, collaboration, and high-stakes competition.
              </p>
            </div>
            <div>
              <h4 className="font-semibold text-sm mb-6 uppercase tracking-wider text-foreground">Product</h4>
              <ul className="space-y-4">
                {["Features", "Competition", "Updates"].map(item => (
                  <li key={item}>
                    <a href="#" className="text-muted-foreground text-sm font-medium hover:text-foreground transition-colors tracking-tight">
                      {item}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <h4 className="font-semibold text-sm mb-6 uppercase tracking-wider text-foreground">Connect</h4>
              <ul className="space-y-4">
                {["Twitter", "Discord", "Contact"].map(item => (
                  <li key={item}>
                    <a href="#" className="text-muted-foreground text-sm font-medium hover:text-foreground transition-colors tracking-tight">
                      {item}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          </div>
          <div className="pt-8 border-t border-border flex flex-col md:flex-row justify-between items-center gap-6">
            <p className="text-xs font-medium text-muted-foreground tracking-tight">
              © {new Date().getFullYear()} InkArena. Precision and Play combined.
            </p>
            <div className="flex gap-8">
              <a href="#" className="text-xs font-medium text-muted-foreground hover:text-foreground transition-colors tracking-tight">
                Privacy Policy
              </a>
              <a href="#" className="text-xs font-medium text-muted-foreground hover:text-foreground transition-colors tracking-tight">
                Terms of Service
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

export default Landing
