import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { useAuth, UserButton } from "@clerk/react";
import { connectSocket, socket, setSocketToken } from "@/services/socket";
import { ThemeSwitcher } from "@/components/ui/theme-switcher";
import LobbyPanel from "@/components/lobby/LobbyPanel";
import { Palette, Share2, Sparkles, Trophy, LayoutDashboard } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";

const Lobby = () => {
  const [connected, setConnected] = useState(socket.connected);
  const [connecting, setConnecting] = useState(!socket.connected);
  const { getToken } = useAuth();

  useEffect(() => {
    const initSocket = async () => {
      try {
        const token = await getToken();
        setSocketToken(token);
        connectSocket();
        setConnecting(true);
      } catch (err) {
        console.error('[Lobby] Failed to get Clerk token:', err);
        setConnecting(false);
      }
    };
    initSocket();

    const onConnect = () => { setConnected(true); setConnecting(false); };
    const onDisconnect = () => { setConnected(false); setConnecting(false); };
    const onConnectErr = () => { setConnected(false); setConnecting(false); };

    socket.on("connect", onConnect);
    socket.on("disconnect", onDisconnect);
    socket.on("connect_error", onConnectErr);

    if (socket.connected) { setConnected(true); setConnecting(false); }

    return () => {
      socket.off("connect", onConnect);
      socket.off("disconnect", onDisconnect);
      socket.off("connect_error", onConnectErr);
    };
  }, [getToken]);

  return (
    <div className="min-h-screen w-full bg-background flex flex-col relative overflow-x-hidden">
      {/* Dynamic Background Elements */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-primary/5 rounded-full blur-[120px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-secondary/5 rounded-full blur-[120px]" />
      </div>

      {/* Header */}
      <header className="relative z-50 flex items-center justify-between px-6 py-4 md:px-12">
        <div className="flex items-center gap-2">
          <Palette className="w-6 h-6 text-primary" />
          <span className="text-xl font-bold tracking-tight text-foreground">InkArena</span>
        </div>
        <div className="flex items-center gap-4">
          <Button asChild variant="ghost" size="icon" className="rounded-full">
            <Link to="/dashboard" title="User Dashboard">
              <LayoutDashboard className="w-5 h-5" />
            </Link>
          </Button>
          <ThemeSwitcher />
          <UserButton afterSignOutUrl="/" />
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 relative z-10 flex flex-col items-center justify-center px-6 py-12">
        <div className="w-full max-w-6xl grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
          
          {/* Left Column: Branding & Features */}
          <div className="flex flex-col gap-8 order-2 lg:order-1">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              className="space-y-4"
            >
              <h2 className="text-4xl md:text-6xl font-bold tracking-tight text-foreground leading-[1.1]">
                Master the Art of the <span className="text-primary">Guess.</span>
              </h2>
              <p className="text-lg text-muted-foreground font-medium max-w-lg leading-relaxed">
                Connect with players worldwide in the most sophisticated real-time drawing arena.
              </p>
            </motion.div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
              {[
                { icon: <Sparkles className="w-5 h-5" />, title: "AI-Powered", desc: "Unique prompts generated by Gemini AI." },
                { icon: <Share2 className="w-5 h-5" />, title: "Instant Share", desc: "Invite friends with a single click." },
                { icon: <Trophy className="w-5 h-5" />, title: "Competitive", desc: "Climb the global leaderboard." },
                { icon: <Palette className="w-5 h-5" />, title: "Precise Tools", desc: "Professional-grade drawing tools." },
              ].map((feature, i) => (
                <motion.div
                  key={feature.title}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.3 + i * 0.1, duration: 0.5 }}
                  className="flex flex-col gap-2 p-4 rounded-2xl bg-card/50 border border-border/50 hover:border-border/80 transition-all shadow-sm"
                >
                  <div className="p-2 w-fit rounded-lg bg-primary/10 text-primary">
                    {feature.icon}
                  </div>
                  <h3 className="font-semibold text-foreground">{feature.title}</h3>
                  <p className="text-sm text-muted-foreground">{feature.desc}</p>
                </motion.div>
              ))}
            </div>
          </div>

          {/* Right Column: Lobby Panel */}
          <div className="flex justify-center lg:justify-end order-1 lg:order-2">
            <LobbyPanel connected={connected} connecting={connecting} />
          </div>

        </div>
      </main>

      {/* Footer */}
      <footer className="relative z-10 px-6 py-8 border-t border-border/50 flex flex-col md:flex-row justify-between items-center gap-4">
        <p className="text-sm text-muted-foreground font-medium italic">
          "The canvas is yours. What will you create?"
        </p>
        <div className="flex gap-6">
          {["Privacy", "Terms", "Discord", "Twitter"].map((link) => (
            <a key={link} href="#" className="text-xs font-semibold text-muted-foreground hover:text-primary transition-colors uppercase tracking-widest">
              {link}
            </a>
          ))}
        </div>
      </footer>
    </div>
  );
};

export default Lobby;
